server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Si la ruta no existe físicamente, devuélvele el control a React (index.html)
    location / {
        try_files $uri $uri/ /index.html;
    }
}